/** ISO 3166-1 alpha-2 国リスト（日本語・英語ラベル） */

export type CountryOption = {
  code: string;
  ja: string;
  en: string;
};

export const WORLD_COUNTRIES: CountryOption[] = [
  { code: "JP", ja: "日本", en: "Japan" },
  { code: "US", ja: "アメリカ合衆国", en: "United States" },
  { code: "KR", ja: "韓国", en: "South Korea" },
  { code: "CN", ja: "中国", en: "China" },
  { code: "TW", ja: "台湾", en: "Taiwan" },
  { code: "HK", ja: "香港", en: "Hong Kong" },
  { code: "MO", ja: "マカオ", en: "Macao" },
  { code: "GB", ja: "イギリス", en: "United Kingdom" },
  { code: "FR", ja: "フランス", en: "France" },
  { code: "DE", ja: "ドイツ", en: "Germany" },
  { code: "IT", ja: "イタリア", en: "Italy" },
  { code: "ES", ja: "スペイン", en: "Spain" },
  { code: "PT", ja: "ポルトガル", en: "Portugal" },
  { code: "NL", ja: "オランダ", en: "Netherlands" },
  { code: "BE", ja: "ベルギー", en: "Belgium" },
  { code: "CH", ja: "スイス", en: "Switzerland" },
  { code: "AT", ja: "オーストリア", en: "Austria" },
  { code: "SE", ja: "スウェーデン", en: "Sweden" },
  { code: "NO", ja: "ノルウェー", en: "Norway" },
  { code: "DK", ja: "デンマーク", en: "Denmark" },
  { code: "FI", ja: "フィンランド", en: "Finland" },
  { code: "IE", ja: "アイルランド", en: "Ireland" },
  { code: "IS", ja: "アイスランド", en: "Iceland" },
  { code: "PL", ja: "ポーランド", en: "Poland" },
  { code: "CZ", ja: "チェコ", en: "Czechia" },
  { code: "SK", ja: "スロバキア", en: "Slovakia" },
  { code: "HU", ja: "ハンガリー", en: "Hungary" },
  { code: "RO", ja: "ルーマニア", en: "Romania" },
  { code: "BG", ja: "ブルガリア", en: "Bulgaria" },
  { code: "GR", ja: "ギリシャ", en: "Greece" },
  { code: "TR", ja: "トルコ", en: "Türkiye" },
  { code: "RU", ja: "ロシア", en: "Russia" },
  { code: "UA", ja: "ウクライナ", en: "Ukraine" },
  { code: "BY", ja: "ベラルーシ", en: "Belarus" },
  { code: "LT", ja: "リトアニア", en: "Lithuania" },
  { code: "LV", ja: "ラトビア", en: "Latvia" },
  { code: "EE", ja: "エストニア", en: "Estonia" },
  { code: "SI", ja: "スロベニア", en: "Slovenia" },
  { code: "HR", ja: "クロアチア", en: "Croatia" },
  { code: "RS", ja: "セルビア", en: "Serbia" },
  { code: "BA", ja: "ボスニア・ヘルツェゴビナ", en: "Bosnia and Herzegovina" },
  { code: "ME", ja: "モンテネグロ", en: "Montenegro" },
  { code: "MK", ja: "北マケドニア", en: "North Macedonia" },
  { code: "AL", ja: "アルバニア", en: "Albania" },
  { code: "XK", ja: "コソボ", en: "Kosovo" },
  { code: "MD", ja: "モルドバ", en: "Moldova" },
  { code: "MT", ja: "マルタ", en: "Malta" },
  { code: "CY", ja: "キプロス", en: "Cyprus" },
  { code: "LU", ja: "ルクセンブルク", en: "Luxembourg" },
  { code: "MC", ja: "モナコ", en: "Monaco" },
  { code: "AD", ja: "アンドラ", en: "Andorra" },
  { code: "LI", ja: "リヒテンシュタイン", en: "Liechtenstein" },
  { code: "SM", ja: "サンマリノ", en: "San Marino" },
  { code: "VA", ja: "バチカン", en: "Vatican City" },
  { code: "CA", ja: "カナダ", en: "Canada" },
  { code: "MX", ja: "メキシコ", en: "Mexico" },
  { code: "GT", ja: "グアテマラ", en: "Guatemala" },
  { code: "BZ", ja: "ベリーズ", en: "Belize" },
  { code: "HN", ja: "ホンジュラス", en: "Honduras" },
  { code: "SV", ja: "エルサルバドル", en: "El Salvador" },
  { code: "NI", ja: "ニカラグア", en: "Nicaragua" },
  { code: "CR", ja: "コスタリカ", en: "Costa Rica" },
  { code: "PA", ja: "パナマ", en: "Panama" },
  { code: "CU", ja: "キューバ", en: "Cuba" },
  { code: "JM", ja: "ジャマイカ", en: "Jamaica" },
  { code: "HT", ja: "ハイチ", en: "Haiti" },
  { code: "DO", ja: "ドミニカ共和国", en: "Dominican Republic" },
  { code: "BS", ja: "バハマ", en: "Bahamas" },
  { code: "BB", ja: "バルバドス", en: "Barbados" },
  { code: "TT", ja: "トリニダード・トバゴ", en: "Trinidad and Tobago" },
  { code: "AG", ja: "アンティグア・バーブーダ", en: "Antigua and Barbuda" },
  { code: "DM", ja: "ドミニカ国", en: "Dominica" },
  { code: "GD", ja: "グレナダ", en: "Grenada" },
  { code: "KN", ja: "セントクリストファー・ネービス", en: "Saint Kitts and Nevis" },
  { code: "LC", ja: "セントルシア", en: "Saint Lucia" },
  { code: "VC", ja: "セントビンセントおよびグレナディーン諸島", en: "Saint Vincent and the Grenadines" },
  { code: "BR", ja: "ブラジル", en: "Brazil" },
  { code: "AR", ja: "アルゼンチン", en: "Argentina" },
  { code: "CL", ja: "チリ", en: "Chile" },
  { code: "CO", ja: "コロンビア", en: "Colombia" },
  { code: "PE", ja: "ペルー", en: "Peru" },
  { code: "VE", ja: "ベネズエラ", en: "Venezuela" },
  { code: "EC", ja: "エクアドル", en: "Ecuador" },
  { code: "BO", ja: "ボリビア", en: "Bolivia" },
  { code: "PY", ja: "パラグアイ", en: "Paraguay" },
  { code: "UY", ja: "ウルグアイ", en: "Uruguay" },
  { code: "GY", ja: "ガイアナ", en: "Guyana" },
  { code: "SR", ja: "スリナム", en: "Suriname" },
  { code: "AU", ja: "オーストラリア", en: "Australia" },
  { code: "NZ", ja: "ニュージーランド", en: "New Zealand" },
  { code: "FJ", ja: "フィジー", en: "Fiji" },
  { code: "PG", ja: "パプアニューギニア", en: "Papua New Guinea" },
  { code: "SB", ja: "ソロモン諸島", en: "Solomon Islands" },
  { code: "VU", ja: "バヌアツ", en: "Vanuatu" },
  { code: "WS", ja: "サモア", en: "Samoa" },
  { code: "TO", ja: "トンガ", en: "Tonga" },
  { code: "TV", ja: "ツバル", en: "Tuvalu" },
  { code: "KI", ja: "キリバス", en: "Kiribati" },
  { code: "NR", ja: "ナウル", en: "Nauru" },
  { code: "PW", ja: "パラオ", en: "Palau" },
  { code: "FM", ja: "ミクロネシア連邦", en: "Micronesia" },
  { code: "MH", ja: "マーシャル諸島", en: "Marshall Islands" },
  { code: "IN", ja: "インド", en: "India" },
  { code: "PK", ja: "パキスタン", en: "Pakistan" },
  { code: "BD", ja: "バングラデシュ", en: "Bangladesh" },
  { code: "LK", ja: "スリランカ", en: "Sri Lanka" },
  { code: "NP", ja: "ネパール", en: "Nepal" },
  { code: "BT", ja: "ブータン", en: "Bhutan" },
  { code: "MV", ja: "モルディブ", en: "Maldives" },
  { code: "AF", ja: "アフガニスタン", en: "Afghanistan" },
  { code: "IR", ja: "イラン", en: "Iran" },
  { code: "IQ", ja: "イラク", en: "Iraq" },
  { code: "SA", ja: "サウジアラビア", en: "Saudi Arabia" },
  { code: "AE", ja: "アラブ首長国連邦", en: "United Arab Emirates" },
  { code: "QA", ja: "カタール", en: "Qatar" },
  { code: "KW", ja: "クウェート", en: "Kuwait" },
  { code: "BH", ja: "バーレーン", en: "Bahrain" },
  { code: "OM", ja: "オマーン", en: "Oman" },
  { code: "YE", ja: "イエメン", en: "Yemen" },
  { code: "JO", ja: "ヨルダン", en: "Jordan" },
  { code: "LB", ja: "レバノン", en: "Lebanon" },
  { code: "SY", ja: "シリア", en: "Syria" },
  { code: "IL", ja: "イスラエル", en: "Israel" },
  { code: "PS", ja: "パレスチナ", en: "Palestine" },
  { code: "GE", ja: "ジョージア", en: "Georgia" },
  { code: "AM", ja: "アルメニア", en: "Armenia" },
  { code: "AZ", ja: "アゼルバイジャン", en: "Azerbaijan" },
  { code: "KZ", ja: "カザフスタン", en: "Kazakhstan" },
  { code: "UZ", ja: "ウズベキスタン", en: "Uzbekistan" },
  { code: "TM", ja: "トルクメニスタン", en: "Turkmenistan" },
  { code: "KG", ja: "キルギス", en: "Kyrgyzstan" },
  { code: "TJ", ja: "タジキスタン", en: "Tajikistan" },
  { code: "MN", ja: "モンゴル", en: "Mongolia" },
  { code: "KP", ja: "北朝鮮", en: "North Korea" },
  { code: "VN", ja: "ベトナム", en: "Vietnam" },
  { code: "TH", ja: "タイ", en: "Thailand" },
  { code: "MY", ja: "マレーシア", en: "Malaysia" },
  { code: "SG", ja: "シンガポール", en: "Singapore" },
  { code: "ID", ja: "インドネシア", en: "Indonesia" },
  { code: "PH", ja: "フィリピン", en: "Philippines" },
  { code: "MM", ja: "ミャンマー", en: "Myanmar" },
  { code: "LA", ja: "ラオス", en: "Laos" },
  { code: "KH", ja: "カンボジア", en: "Cambodia" },
  { code: "BN", ja: "ブルネイ", en: "Brunei" },
  { code: "TL", ja: "東ティモール", en: "Timor-Leste" },
  { code: "EG", ja: "エジプト", en: "Egypt" },
  { code: "LY", ja: "リビア", en: "Libya" },
  { code: "TN", ja: "チュニジア", en: "Tunisia" },
  { code: "DZ", ja: "アルジェリア", en: "Algeria" },
  { code: "MA", ja: "モロッコ", en: "Morocco" },
  { code: "SD", ja: "スーダン", en: "Sudan" },
  { code: "SS", ja: "南スーダン", en: "South Sudan" },
  { code: "ET", ja: "エチオピア", en: "Ethiopia" },
  { code: "ER", ja: "エリトリア", en: "Eritrea" },
  { code: "DJ", ja: "ジブチ", en: "Djibouti" },
  { code: "SO", ja: "ソマリア", en: "Somalia" },
  { code: "KE", ja: "ケニア", en: "Kenya" },
  { code: "UG", ja: "ウガンダ", en: "Uganda" },
  { code: "TZ", ja: "タンザニア", en: "Tanzania" },
  { code: "RW", ja: "ルワンダ", en: "Rwanda" },
  { code: "BI", ja: "ブルンジ", en: "Burundi" },
  { code: "NG", ja: "ナイジェリア", en: "Nigeria" },
  { code: "GH", ja: "ガーナ", en: "Ghana" },
  { code: "CI", ja: "コートジボワール", en: "Côte d'Ivoire" },
  { code: "SN", ja: "セネガル", en: "Senegal" },
  { code: "ML", ja: "マリ", en: "Mali" },
  { code: "BF", ja: "ブルキナファソ", en: "Burkina Faso" },
  { code: "NE", ja: "ニジェール", en: "Niger" },
  { code: "TD", ja: "チャド", en: "Chad" },
  { code: "CM", ja: "カメルーン", en: "Cameroon" },
  { code: "CF", ja: "中央アフリカ", en: "Central African Republic" },
  { code: "GA", ja: "ガボン", en: "Gabon" },
  { code: "CG", ja: "コンゴ共和国", en: "Congo" },
  { code: "CD", ja: "コンゴ民主共和国", en: "DR Congo" },
  { code: "AO", ja: "アンゴラ", en: "Angola" },
  { code: "ZM", ja: "ザンビア", en: "Zambia" },
  { code: "ZW", ja: "ジンバブエ", en: "Zimbabwe" },
  { code: "MW", ja: "マラウイ", en: "Malawi" },
  { code: "MZ", ja: "モザンビーク", en: "Mozambique" },
  { code: "BW", ja: "ボツワナ", en: "Botswana" },
  { code: "NA", ja: "ナミビア", en: "Namibia" },
  { code: "ZA", ja: "南アフリカ", en: "South Africa" },
  { code: "LS", ja: "レソト", en: "Lesotho" },
  { code: "SZ", ja: "エスワティニ", en: "Eswatini" },
  { code: "MG", ja: "マダガスカル", en: "Madagascar" },
  { code: "MU", ja: "モーリシャス", en: "Mauritius" },
  { code: "SC", ja: "セーシェル", en: "Seychelles" },
  { code: "KM", ja: "コモロ", en: "Comoros" },
  { code: "CV", ja: "カーボベルデ", en: "Cabo Verde" },
  { code: "GM", ja: "ガンビア", en: "Gambia" },
  { code: "GN", ja: "ギニア", en: "Guinea" },
  { code: "GW", ja: "ギニアビサウ", en: "Guinea-Bissau" },
  { code: "SL", ja: "シエラレオネ", en: "Sierra Leone" },
  { code: "LR", ja: "リベリア", en: "Liberia" },
  { code: "TG", ja: "トーゴ", en: "Togo" },
  { code: "BJ", ja: "ベナン", en: "Benin" },
  { code: "GQ", ja: "赤道ギニア", en: "Equatorial Guinea" },
  { code: "ST", ja: "サントメ・プリンシペ", en: "São Tomé and Príncipe" },
  { code: "MR", ja: "モーリタニア", en: "Mauritania" },
];

export function countryLabel(code: string | null | undefined, locale: "ja" | "en"): string {
  if (!code) return "";
  const hit = WORLD_COUNTRIES.find((c) => c.code === code);
  if (!hit) return code;
  return locale === "en" ? hit.en : hit.ja;
}

export function sortedCountries(locale: "ja" | "en"): CountryOption[] {
  return [...WORLD_COUNTRIES].sort((a, b) => {
    const la = locale === "en" ? a.en : a.ja;
    const lb = locale === "en" ? b.en : b.ja;
    return la.localeCompare(lb, locale === "en" ? "en" : "ja");
  });
}
